[32m2024-03-04 18:29:00 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 9d4d4c11-7caf-47f8-9bca-a38b2ee96827 - 50016 - LOGS_CAPTURED - Started capturing logs in process (pid: 50016).
[32m2024-03-04 18:29:00 +0100[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 9d4d4c11-7caf-47f8-9bca-a38b2ee96827 - 50016 - monitoringAndReporting - STEP_START - Started execution of step "monitoringAndReporting".
[32m2024-03-04 18:29:00 +0100[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 9d4d4c11-7caf-47f8-9bca-a38b2ee96827 - 50016 - monitoringAndReporting - STEP_FAILURE - Execution of step "monitoringAndReporting" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "monitoringAndReporting"::

TypeError: upload_file() missing 1 required positional argument: 'Key'

Stack Trace:
  File "/opt/homebrew/lib/python3.11/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/opt/homebrew/lib/python3.11/site-packages/dagster/_utils/__init__.py", line 467, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 131, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dagster/_core/execution/plan/compute_generator.py", line 125, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marcelthomas/Development/MLOPS/my-dagster-project/quickstart_etl/assets/prod-pipeline.py", line 412, in monitoringAndReporting
    s3_client.upload_file(reportsBucket, path)
[0m
